# -*- coding: utf-8 -*-
"""Remove.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxDyx7PSxZOH6ifJwIGWe881rtnJlmG4
"""

#WORKS
def remove_related_lines(text):
    lines = text.split('\n')
    related_index = None

    # Find the line index containing the word "Related"
    for i, line in enumerate(lines):
        if "RELATED" in line:
            related_index = i
            break

    # Remove the line containing "Related" and the three lines after it
    if related_index is not None:
        del lines[related_index:related_index + 3]

    # Join the modified lines back into a single string
    result_text = '\n'.join(lines)
    return result_text

# Example usage
user_input = """
This is a sample text.
It contains some lines of text.
Related: This is the line with the word "Related".
This is the first line after the Related line.
This is the second line after the Related line.
This is the third line after the Related line.
This is an unrelated line.

"""

modified_text = remove_related_lines(user_input)
print(modified_text)

"""Test Text"""

"""
hello hi hi
my name is slim shady
Related
hello hi
hello ho
hello hello
"""

"""
This is a sample text.
It contains some lines of text.
Related: This is the line with the word "Related".
This is the first line after the Related line.
This is the second line after the Related line.
This is the third line after the Related line.
This is an unrelated line.
"""